language: r
cache: packages
pandoc_version: 2.9.2.1

addons:
  apt:
    packages:
    - cargo
    - libpoppler-cpp-dev
    - libmagick++-dev
    - asymptote

services:
  - xvfb

script:
  - xvfb-run -a make gitbook
  - ./_deploy.sh

# before_script:
#   - chmod +x ./_build.sh
#   - chmod +x ./_deploy.sh
#
# script:
#   - ./_build.sh
#   - ./_deploy.sh
